<a href="https://colab.research.google.com/github/Cemile-Yaxin/WIX1002-25066696/blob/main/Python25066696.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np
a=np.full((2,2),10)
print(a)

[[10 10]
 [10 10]]


In [ ]:
b=np.random.random((3,4))
print(b)

[[0.3978105  0.52957107 0.98170822 0.27611629]
 [0.261475   0.22630228 0.87838396 0.76802452]
 [0.28570277 0.46615141 0.7903827  0.16015208]]


In [12]:
c=np.ones((2,2))
d=np.zeros((2,4))
print(c)
print(d)

[[1. 1.]
 [1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [41]:
e=np.random.random((6,3))
print(e)
f=np.zeros((3,6))
for i in range(3):
  for j in range(6):
    f[i,j]=e[j,i]
print(f)

[[0.72976266 0.2342757  0.6883389 ]
 [0.89731583 0.77811318 0.78687366]
 [0.52803665 0.74975119 0.30889354]
 [0.83465826 0.68947689 0.30053049]
 [0.89948216 0.98331062 0.13207729]
 [0.46588979 0.07838538 0.16819772]]
[[0.72976266 0.89731583 0.52803665 0.83465826 0.89948216 0.46588979]
 [0.2342757  0.77811318 0.74975119 0.68947689 0.98331062 0.07838538]
 [0.6883389  0.78687366 0.30889354 0.30053049 0.13207729 0.16819772]]


In [40]:
n=int(input("Please enter n: "))
p=int(input("Please enter p: "))
m=int(input("Please enter m: "))
arr1=np.random.random((n,p))
arr2=np.random.random((p,m))
print(arr1)
print(arr2)
arr=np.zeros((n,m))
for i in range (n):
  for j in range(m):
    for k in range(p):
      arr[i,j]=arr1[i,k]*arr2[k,j]
print(arr)


Please enter n: 2
Please enter p: 3
Please enter m: 4
[[0.64938235 0.86975739 0.83217033]
 [0.95502268 0.50022682 0.45043675]]
[[0.51659574 0.60841166 0.68985798 0.39230314]
 [0.05660057 0.12815174 0.5774833  0.72894754]
 [0.74369399 0.13257101 0.70166266 0.13195966]]
[[0.61888007 0.11032166 0.58390285 0.10981292]
 [0.3349871  0.05971485 0.31605465 0.05943948]]
